# Generated by Django 6.1 on 2026-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('room_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
